name: Maven Package

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build-app:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.7-openjdk-18-slim
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

  test:
    needs: build-app
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.7-openjdk-18-slim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Unit Tests
        run: mvn test